version: '3.8'

services:
  backend:
    build:
      context: ./backend          
      dockerfile: backend.Dockerfile
    ports:
      - "9001:9001"
      - "9002:9002"
      - "9003:9003"
      - "9004:9004"
    # volumes:
    #   - .:/app
    networks:
      - intents-network

  frontend:
    build:
      context: ./frontend        
      dockerfile: frontend.Dockerfile
    ports:
      - "9000:9000"
    networks:
      - intents-network
    # depends_on:
    #   - backend

networks:
  intents-network:
    driver: bridge
