version: '3.8'

services:
  frontend:
    build:
      context: ./frontend         
      dockerfile: frontend.Dockerfile
    ports:
      - "9000:9000"
    networks:
      - intents-network
  backend_api:
    build:
      context: ./backend/api          
      dockerfile: backend_api.Dockerfile
    ports:
      - "9001:9001"
    networks:
      - intents-network
  intents:
    build:
      context: ./backend/Modules/IntentSpecification2WorkflowGenerator          
      dockerfile: intents.Dockerfile
    ports:
      - "9002:9002"
    networks:
      - intents-network
  anticipation:
    build:
      context: ./backend/Modules/IntentAnticipation          
      dockerfile: anticipation.Dockerfile
    ports:
      - "9003:9003"
      - "9004:9004"
    networks:
      - intents-network



networks:
  intents-network:
    driver: bridge
