DELETE {

    ?subject <http://www.e-lico.eu/ontologies/dmo/DMOP/DMOP.owl#hasDataPrimitiveTypeColumn> ?insVal_1 .
    
}
INSERT {

    ?subject <http://www.e-lico.eu/ontologies/dmo/DMOP/DMOP.owl#hasDataPrimitiveTypeColumn> <http://www.e-lico.eu/ontologies/dmo/DMOP/DMOP.owl#CategoricalOrNumeric> .
    
}
WHERE {

    ?base a dmop:TabularDataset .
    ?base dmop:hasColumn ?subject .
    VALUES ?subject { $$COLUMNS_TO_TRANSFORM$$ }
    OPTIONAL { ?subject <http://www.e-lico.eu/ontologies/dmo/DMOP/DMOP.owl#hasDataPrimitiveTypeColumn> ?insVal_1 . }
    ?subject <http://www.e-lico.eu/ontologies/dmo/DMOP/DMOP.owl#isFeature> true.
    


}